// Generates js/config.js from environment variables.
// Run by GitHub Actions before `netlify deploy`. Locally, devs copy
// js/config.example.js → js/config.js by hand.

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

const url = process.env.SUPABASE_URL;
const anon = process.env.SUPABASE_ANON_KEY;

if (!url || !anon) {
  console.error('build-config: SUPABASE_URL and SUPABASE_ANON_KEY are required.');
  process.exit(1);
}

const out = `// Auto-generated by scripts/build-config.mjs. Do not edit.
window.YEPGENT_CONFIG = Object.freeze({
  supabaseUrl: ${JSON.stringify(url)},
  supabaseAnonKey: ${JSON.stringify(anon)}
});
`;

const target = 'js/config.js';
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, out, 'utf8');
console.log(`build-config: wrote ${target} (${out.length} bytes).`);
